//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during deleting the back part of the video.
        /// </summary>
        internal static string AfterDeleteErrorMessage {
            get {
                return ResourceManager.GetString("AfterDeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during deleting the front part of the video.
        /// </summary>
        internal static string BeforeDeleteErrorMessage {
            get {
                return ResourceManager.GetString("BeforeDeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occuured while merging files.
        /// </summary>
        internal static string BehindMergeErrorMessage {
            get {
                return ResourceManager.GetString("BehindMergeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during deleting the recorded video file.
        /// </summary>
        internal static string DeleteErrorMessage {
            get {
                return ResourceManager.GetString("DeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identically named file already exists.
        /// </summary>
        internal static string DuplicateSaveErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identical lecture title already exists.
        /// </summary>
        internal static string DuplicationLectureErrorMessage {
            get {
                return ResourceManager.GetString("DuplicationLectureErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while move to the editing screen.
        /// </summary>
        internal static string EditScreenChangeErrorMessage {
            get {
                return ResourceManager.GetString("EditScreenChangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the encoding process.
        /// </summary>
        internal static string EncodingErrorMessage {
            get {
                return ResourceManager.GetString("EncodingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoding process is completed.
        /// </summary>
        internal static string EncodingSuccessMessage {
            get {
                return ResourceManager.GetString("EncodingSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the front merging process.
        /// </summary>
        internal static string FrontMergeErrorMessage {
            get {
                return ResourceManager.GetString("FrontMergeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the file list.
        /// </summary>
        internal static string GetFileListErrorMessage {
            get {
                return ResourceManager.GetString("GetFileListErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the lecture material.
        /// </summary>
        internal static string LectureFileNameError {
            get {
                return ResourceManager.GetString("LectureFileNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the subtitle of the lecture.
        /// </summary>
        internal static string LectureModuleTitleError {
            get {
                return ResourceManager.GetString("LectureModuleTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the login information.
        /// </summary>
        internal static string LoginDefaultError {
            get {
                return ResourceManager.GetString("LoginDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network-related error has occurred.
        /// </summary>
        internal static string LoginEtcErrorMessage {
            get {
                return ResourceManager.GetString("LoginEtcErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your ID again.
        /// </summary>
        internal static string LoginIDFailErrorMessage {
            get {
                return ResourceManager.GetString("LoginIDFailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your password again.
        /// </summary>
        internal static string LoginPasswordErrorMessage {
            get {
                return ResourceManager.GetString("LoginPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while initializing the media window.
        /// </summary>
        internal static string MediaWindowInitialiizingErrorMessage {
            get {
                return ResourceManager.GetString("MediaWindowInitialiizingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save the current status of work before continuing the next process.
        /// </summary>
        internal static string NotSavedErrorMessage {
            get {
                return ResourceManager.GetString("NotSavedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while pausing the video file.
        /// </summary>
        internal static string PauseErrorMessage {
            get {
                return ResourceManager.GetString("PauseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while playing the video file.
        /// </summary>
        internal static string PlayErrorMessage {
            get {
                return ResourceManager.GetString("PlayErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while recording the video file.
        /// </summary>
        internal static string RecordingErrorMessage {
            get {
                return ResourceManager.GetString("RecordingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video has been saved sucessfully.
        /// </summary>
        internal static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the file.
        /// </summary>
        internal static string SavingErrorMessage {
            get {
                return ResourceManager.GetString("SavingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while stopping the video recording.
        /// </summary>
        internal static string StopErrorMessage {
            get {
                return ResourceManager.GetString("StopErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the media file.
        /// </summary>
        internal static string TakeMediaErrorMessage {
            get {
                return ResourceManager.GetString("TakeMediaErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading the file to the server.
        /// </summary>
        internal static string UploadErrorMessage {
            get {
                return ResourceManager.GetString("UploadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fil has been uploaded to the server successfully.
        /// </summary>
        internal static string UploadSuccessMessage {
            get {
                return ResourceManager.GetString("UploadSuccessMessage", resourceCulture);
            }
        }
    }
}
